name: Sanity Test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  test_model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas==1.1.5 numpy==1.17.3 scikit-learn==0.23.2 cml

      - name: Run unit tests
        run: |
          python -m test.py --verbose > test_output.txt 2>&1

      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Test Results" >> report.md
          cat test_output.txt >> report.md
          echo "## Model Metrics" >> report.md
          cat metrics.txt >> report.md
          cml comment create --publish --pr report.md
